import { type NextPage } from "next";
import Head from "next/head";

import { UserButton } from "@clerk/nextjs";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const { data } = api.posts.getAll.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <UserButton />
      </header>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <h3 className="text-white">Sample Text</h3>
        <div>
          {data?.map((el) => (
            <p key={el.id}>{el.content}</p>
          ))}
        </div>
      </main>
    </>
  );
};

export default Home;
